sudo: false
language: node_js
node_js:
  - "6"
  - "5"

services:
  - docker

before_install:
  - docker pull elcolio/etcd
  - docker run -d -p 2379:2379 elcolio/etcd

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
