sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"

services:
  - docker

before_install:
  - docker pull quay.io/coreos/etcd
  - docker run -d -p 2379:2379 quay.io/coreos/etcd -advertise-client-urls http://127.0.0.1:2379 -listen-client-urls http://127.0.0.1:2379

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls